{% set name = "blackjax" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb708f183d714750feb475fb87b8162fc1641309f30ee42fd38a5dec82733868

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - jaxlib >=0.3.10
    - jax >=0.3.13
    - jaxopt >=0.4.2
    - fastprogress >=0.2.0

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/blackjax-devs/blackjax
  summary: BlackJAX is a sampling library designed for ease of use, speed and modularity
  description: |
    BlackJAX is a sampling library designed for ease of use, speed and modularity  
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://blackjax-devs.github.io/blackjax/
  dev_url: https://github.com/blackjax-devs/blackjax

extra:
  recipe-maintainers:
    - junpenglao
    - rlouf
    - dirmeier
