{% set name = "blackjax" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc6233ccaff8996a626d99cf9a039e4e98ec2a497f088b910705509f89c3d212

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.9.0
    - jaxlib >=0.9.0
    - numpy >=1.25
    - optax >=0.2.3
    - scipy >=1.13
    - typing_extensions >=4.4.0

  run_constrained:
    - fastprogress >=1.0.0,<1.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - blackjax

about:
  home: https://github.com/blackjax-devs/blackjax
  summary: BlackJAX is a sampling library designed for ease of use, speed and modularity
  description: |
    BlackJAX is a sampling library designed for ease of use, speed and modularity  
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://blackjax-devs.github.io/blackjax/
  dev_url: https://github.com/blackjax-devs/blackjax

extra:
  recipe-maintainers:
    - albcab
    - junpenglao
    - rlouf
    - albcab
    - dirmeier
