{% set name = "blackjax" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6814d09aa963b821c961844a61ac5b9925f21d19ad2ebc741320ceae0d4dbcb5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - fastprogress >=1.0.0
    - jax >=0.4.16
    - jaxlib >=0.4.16
    - jaxopt >=0.8
    - optax >=0.1.7
    - typing_extensions >=4.4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - blackjax

about:
  home: https://github.com/blackjax-devs/blackjax
  summary: BlackJAX is a sampling library designed for ease of use, speed and modularity
  description: |
    BlackJAX is a sampling library designed for ease of use, speed and modularity  
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://blackjax-devs.github.io/blackjax/
  dev_url: https://github.com/blackjax-devs/blackjax

extra:
  recipe-maintainers:
    - albcab
    - junpenglao
    - rlouf
    - albcab
    - dirmeier
