{% set name = "blackjax" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8fedfc8de2ad33e4c170de4648d8301374e386fd68d8db91bf03f1bd2d0f5e97

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - fastprogress >=1.0.0
    - jax >=0.4.16
    - jaxlib >=0.4.14
    - jaxopt >=0.8
    - optax >=0.1.7
    - typing-extensions >=4.4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name }}

about:
  home: https://github.com/blackjax-devs/blackjax
  summary: BlackJAX is a sampling library designed for ease of use, speed and modularity
  description: |
    BlackJAX is a sampling library designed for ease of use, speed and modularity  
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://blackjax-devs.github.io/blackjax/
  dev_url: https://github.com/blackjax-devs/blackjax

extra:
  recipe-maintainers:
    - albcab
    - junpenglao
    - rlouf
    - albcab
    - dirmeier
